set(LIB_SOURCES "")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/copy-acl.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/set-acl.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/acl-errno-valid.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/acl-internal.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/get-permissions.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/set-permissions.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/alignalloc.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/allocator.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/areadlink.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/areadlink-with-size.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/areadlinkat.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/areadlinkat-with-size.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/argmatch.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/argv-iter.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/openat-proc.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/backupfile.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/backup-rename.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/backupfile.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/backup-find.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/base32.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/base64.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/basename-lgpl.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/binary-io.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/bitrotate.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/btoc32.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/buffer-lcm.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/c-ctype.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/c-file-type.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/c-strcasecmp.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/c-strncasecmp.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/c-strtod.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/c-strtold.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32_apply_type_test.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32_get_type_test.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32isalnum.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32isalpha.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32isblank.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32iscntrl.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32isdigit.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32isgraph.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32islower.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32isprint.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32ispunct.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32isspace.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32isupper.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32isxdigit.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32tolower.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/c32width.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/canon-host.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/canonicalize.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/careadlinkat.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/chdir-long.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/chmodat.c")
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/chown.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/chownat.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/cl-strtod.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/cl-strtold.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/cloexec.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/close-stream.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/issymlink.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/issymlinkat.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/crc.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/sha3.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/sha3-stream.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/closein.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/closeout.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/copy-file-range.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/count-leading-zeros.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/af_alg.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/md5-stream.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/md5.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sha1-stream.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sha1.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sha256-stream.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sha256.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sha512-stream.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sha512.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sm3-stream.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sm3.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/cycle-check.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/di-set.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/opendir-safer.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/dirname.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/basename.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/dirname-lgpl.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/stripslash.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/dtoastr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/dtotimespec.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/error.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/euidaccess.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/exclude.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/exitfail.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/explicit_bzero.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fadvise.c")
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fchownat.c")
endif()
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fclose.c")
endif()
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fcntl.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/creat-safer.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/open-safer.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fd-hook.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fd-reopen.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fd-safer-flag.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/dup-safer-flag.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fdutimensat.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fflush.c")
endif()
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/findprog-in.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/concat-filename.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/file-has-acl.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/file-set.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/file-type.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/filemode.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/filenamecat.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/filenamecat-lgpl.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/filevercmp.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fopen-safer.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fpending.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fprintftime.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fpurge.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/freadahead.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/freading.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/freadptr.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/freadseek.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/free.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/freopen-safer.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fseek.c")
endif()
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fseeko.c")
endif()
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fseterr.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fsusage.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/ftoastr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fts.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/full-read.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/full-write.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/futimens.c")
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getcwd.c")
endif()
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getcwd-lgpl.c")
endif()
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getdelim.c")
endif()
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getgroups.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/gethrxtime.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xtime.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getndelim2.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getopt.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getopt1.c")
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getprogname.c")
endif()
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getrandom.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/gettime.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/gettime-res.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getugroups.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/malloc/dynarray_at_failure.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/malloc/dynarray_emplace_enlarge.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/malloc/dynarray_finalize.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/malloc/dynarray_resize.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/malloc/dynarray_resize_clear.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/malloc/scratch_buffer_grow.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/malloc/scratch_buffer_grow_preserve.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/malloc/scratch_buffer_set_array_size.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/group-member.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/hard-locale.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/hash.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/hash-pjw.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/hash-triple.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/hash-triple-simple.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/heap.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/human.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/i-ring.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/ialloc.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/idcache.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/ino-map.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/imaxtostr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/inttostr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/offtostr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/uinttostr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/umaxtostr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/isapipe.c")
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/lchown.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/ldtoastr.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/mini-gmp-gnulib.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/linebuffer.c")
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/linkat.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/localcharset.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/glthread/lock.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/long-options.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/malloca.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/math.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/mcel.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gl/lib/mbbuf.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbchar.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/mbrtoc32.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbsalign.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbscasecmp.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbschr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbslen.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbsrtoc32s.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbswidth.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbszero.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbuiter.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbuiterf.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/memcasecmp.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/memchr2.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/memcmp2.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/memcoll.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mempcpy.c")
endif()
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/memrchr.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/memset_explicit.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mgetgroups.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mkancesdirs.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/dirchownmod.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mkdir-p.c")
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mknod.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/modechange.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mountlist.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mpsort.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/nanosleep.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/nl_langinfo.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/nproc.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/nstrftime.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/obstack.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/openat-die.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/openat-safer.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/opendirat.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/parse-datetime.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/physmem.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/pipe2.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/posixtm.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/posixver.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/printf-frexp.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/printf-frexpl.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/priv-set.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/progname.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/propername-lite.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/pthread-mutex.c")
endif()
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/pthread_mutex_timedlock.c")
endif()
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/putenv.c")
endif()
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/qcopy-acl.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/qset-acl.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/quotearg.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/randint.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/randperm.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/randread.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/rand-isaac.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/rawmemchr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/read-file.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/readtokens.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/readtokens0.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/readutmp.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/reallocarray.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/regex.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/renameatu.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/root-dev-ino.c")
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/rpmatch.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/safe-read.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/safe-write.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/same-inode.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/same.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/save-cwd.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/savedir.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/savewd.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/secure_getenv.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/selinux-at.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/se-context.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/se-label.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/se-selinux.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/setlocale_null.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/setlocale-lock.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/settime.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sig2str.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sig-handler.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sockets.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/stat-time.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mkstemp-safer.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/strerror.c")
endif()
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/strerror-override.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/strnlen1.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/strintcmp.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/strnumcmp.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/strtoll.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/strtoull.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/sys_socket.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/targetdir.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/tempname.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/glthread/threadlib.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/time_rz.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/timegm.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/timespec.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/glthread/tls.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/tmpdir.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/u64.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unicase/tolower.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unicodeio.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_alnum.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_alpha.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_blank.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_cntrl.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_digit.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_graph.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_lower.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_print.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_punct.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_space.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_upper.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unictype/ctype_xdigit.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unistd.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/dup-safer.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fd-safer.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/pipe-safer.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unistr/u32-chr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unistr/u32-cpy.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unistr/u32-pcpy.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unistr/u32-strcat.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unistr/u32-strlen.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unistr/u8-mbtoucr.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unistr/u8-uctomb.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unistr/u8-uctomb-aux.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/uniwidth/width.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/unlinkdir.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/userspec.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/utimecmp.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/utimens.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/utimensat.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/verror.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/version-etc.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/version-etc-fsf.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/wctype-h.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/wmempcpy.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/write-any-file.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xalignalloc.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xmalloc.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xalloc-die.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xbinary-io.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gl/lib/xdectoimax.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gl/lib/xdectoumax.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xfts.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xgetcwd.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xgetgroups.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xgethostname.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xmemcoll.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xnanosleep.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xprintf.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xreadlink.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xsize.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/xstrtod.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/xstrtoimax.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/xstrtol.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/xstrtoul.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/xstrtol-error.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/xstrtold.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/xstrtoumax.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/xsetenv.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/xmemdup0.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/mbs_endswith.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/mbsstr.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/strerrorname_np.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gnulib/lib/errno-iter.c")
list(APPEND LIB_SOURCES "${CMAKE_SOURCE_DIR}/../gl/lib/skipchars.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xvasprintf.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/xasprintf.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/yesno.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mktime.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/getpass.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/mbsrtoc32s-state.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/vfprintf.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/vprintf.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/vasprintf.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/asnprintf.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fopen.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/fnmatch.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/printf-args.c")
if(NOT APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/at-func2.c")
endif()
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/vasnprintf.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/printf-parse.c")
list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/asprintf.c")
if(APPLE)
  list(APPEND LIB_SOURCES "${coreutils_release_SOURCE_DIR}/lib/acl_entries.c")
endif()
